### ISSUE TITLE
Any further updates?

### ISSUE THREAD

**Issue by Fatdolphins** [Mumfrey/MacrosAPI#2]
Id like to know if there are any further updates to this mod. I would like to see it on 1.9 and on forge if possible.

**Comment by Mumfrey** [comment]
There's a perfectly serviceable forum thread for this, but you know damn well that asking for updates is banned on mcforum, so you come and harrass me here instead?

Yes of course there will be updates for the mod, but badgering me about it will get you nowhere.

And no, it'll never be on Forge.
